apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
      {{- if eq .Values.externalDns.provider "aws" }}
      external-dns.alpha.kubernetes.io/aws-weight: {{ .Values.externalDns.awsWeight | quote }}
      external-dns.alpha.kubernetes.io/set-identifier: "{{ .Values.cluster.name }}-{{ .Values.externalDns.type }}"
      external-dns.alpha.kubernetes.io/ttl: {{ .Values.externalDns.ttl | quote }}
      {{- end }}
spec:
  parentRefs:
    - kind: Gateway
      group: gateway.networking.k8s.io
      name: {{ if eq .Values.externalDns.type "private" }}internal{{ else }}external{{ end }}-gateway
      namespace: gateways
  hostnames:
    - {{ .Values.host | quote }}
  rules:
    - backendRefs:
      {{- range .Values.dispatcher.ports }}
        - name: "{{ $.Release.Name }}-dispatcher"
          port: {{ .port }}
          kind: Service
       {{- end }}
    - matches:
      - path:
          type: PathPrefix
          value: /operations/assets/assets
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /operations/assets
              type: ReplacePrefixMatch
      backendRefs:
      {{- range .Values.dispatcher.ports }}
        - name: "{{ $.Release.Name }}-dispatcher"
          port: {{ .port }}
          kind: Service
       {{- end }}
