securityContext: {}

enabledCilium: false

externalSecrets:
  refreshInterval: 1h
  secretStoreName: awssm-cluster-secret-store
  secrets:
    - envVarName: CURRENT_SERVICE_ENCRYPTION_KEY
      k8sSecretKey: currentServiceEncryptionKey
      remoteKey: identity-operations-processor/core/encryption-key-storer
      remoteProperty: currentServiceEncryptionKey
    - envVarName: PREVIOUS_SERVICE_ENCRYPTION_KEY
      k8sSecretKey: previousServiceEncryptionKey
      remoteKey: identity-operations-processor/core/encryption-key-storer
      remoteProperty: previousServiceEncryptionKey
    - envVarName: GRPC_AUTH_API_KEYS
      k8sSecretKey: grpcAuthApiKeys
      remoteKey: identity-operations-processor/core/encryption-key-storer
      remoteProperty: grpcAuthApiKeys

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuAverageUtilization: 120
  memoryAverageUtilization: 120

karpenter:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 168h
  requirements:
    instanceFamilies:
      - c6i
    instanceCpus:
      - "4"
