apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    version: {{ .Values.encryptionKeyStorer.tag }}
    app: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
  data:
{{- range .Values.externalSecrets.secrets }}
  - secretKey: {{ .k8sSecretKey }}
    remoteRef:
      key: {{ .remoteKey }}
      property: {{ .remoteProperty }}
{{- end }}
