apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Release.Name }}
spec:
  disruption:
    {{- toYaml .Values.karpenter.disruption | nindent 4 }}
  limits:
    cpu: 1k
    memory: 1000Gi
  template:
    metadata:
      labels:
        facephi.aws/nodepool: {{ .Release.Name }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            {{- toYaml .Values.karpenter.requirements.instanceFamilies | nindent 12 }}
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            {{- toYaml .Values.karpenter.requirements.instanceCpus | nindent 12 }}
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - {{ .Values.karpenter.region }}a
            - {{ .Values.karpenter.region }}b
            - {{ .Values.karpenter.region }}c
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
