name: Notify on PR Ready for Review 🔔

on:
  pull_request:
    types: [ready_for_review, opened]

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    name: Notify Microsoft Teams Channel 🔔
    steps:
      - name: Send message to Microsoft Teams Channel
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          REPO_NAME="${{ github.event.repository.name }}"

          curl -H 'Content-Type: application/json' -d '{
            "title": "🚀 ['"$REPO_NAME"']: PR Ready for Review",
            "text": "**🔖 Title:** '"$PR_TITLE"'\n**👤 Author:** '"$PR_AUTHOR"'\n\n**🌿 Branch:** '"$PR_BRANCH"'\n\n---\n\n[👉 View Pull Request]('"$PR_URL"')"
          }' $TEAMS_WEBHOOK_URL
